# Generated by Django 5.2.4 on 2025-07-25 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0002_alter_outgoingorder_discount'),
        # ('suppliers', '0001_initial'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='incomingorder',
        #     name='supplier',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.supplier'),
        # ),
        migrations.AlterField(
            model_name='outgoingorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customer'),
        ),
    ]
