# Generated by Django 5.2.4 on 2025-07-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='no description', max_length=500),
            preserve_default=False,
        ),
    ]
