# Generated by Django 5.2 on 2025-07-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_available_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_quantity',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
