# Generated by Django 5.2.4 on 2025-07-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_supplier_customer_ptr_delete_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_quantity',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
